name: codesync

services:
  backend:
    container_name: codesync-backend
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sandbox-data:/app/sandbox

  database:
    container_name: codesync-database
    image: mysql:9
    volumes:
      - database:/var/lib/mysql

  javascript-sandbox:
    build: ./sandbox
    image: javascript-sandbox-image
    profiles:
      - sandbox

volumes:
  sandbox-data:
  database:
