services:
  codesync-app:
    container_name: codesync-server-app
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    container_name: codesync-database
    image: mysql:9
    volumes:
      - codesync-db:/var/lib/mysql

  javascript-sandbox:
    image: node:25
    container_name: codesync-javascript-sandbox
    network_mode: none
    working_dir: /usr/src/app
    volumes:
      - ./sandbox:/usr/src/app
    profiles:
      - sandbox

volumes:
  codesync-db:
