services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm run start
  
  worker:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: node dist/services/worker.service.js

  database:
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}