#builder ---
FROM node:25 AS builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

#runner ---
FROM node:25 AS runner

RUN apt-get update && apt-get install -y docker.io

WORKDIR /app

COPY package.json .

RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 8000

CMD [ "npm", "run", "start" ]