services:
  backend:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm run start
  database:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORDS: true
