name: codesync

services:
  backend:
    container_name: codesync-backend
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sandbox-data:/app/sandbox
      - uploads:/app/tmp/uploads
    depends_on:
      - database

  database:
    container_name: codesync-database
    image: mysql:9
    volumes:
      - database:/var/lib/mysql

  sandbox-cleaner:
    build: ./cleaner
    image: sandbox-cleaner-image
    profiles:
      - sandbox

  javascript-sandbox:
    build:
      context: ./sandbox
      dockerfile: Dockerfile.js
    image: javascript-sandbox-image
    profiles:
      - sandbox

  php-sandbox:
    build:
      context: ./sandbox
      dockerfile: Dockerfile.php
    image: php-sandbox-image
    profiles:
      - sandbox

volumes:
  sandbox-data:
  database:
  uploads:
