services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npx tsx src/services/worker.service.ts

  database:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
