FROM node:25

RUN apt-get update && apt-get install -y docker.io

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ENV NODE_ENV=development
ENV PORT=8000

EXPOSE 8000

CMD ["npm", "run", "dev"]